# Generated by Django 4.1.3 on 2022-11-30 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='documento',
        ),
        migrations.AddField(
            model_name='servico',
            name='documentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerencia.documento'),
        ),
    ]
